ntot = max_valid_node

!resetting some counters #####
max_stress_n = 0				!#
max_stress_t = 0
min_stress_n = 1e15			!#
min_stress_t = 1e15
min_dN = 1e15				!#
							!#
nodes_to_kill_n = 0			!#
nodes_to_kill_t = 0
max_psi_n = 0					!#
second_to_max_psi_n = 0		!#
max_psi_t = 0
second_to_max_psi_t = 0
may_die_n = 0					!#
may_die_static = 0			!#
may_die_low_high = 0		!#
may_die_very_high = 0		!#
may_die_t = 0
!#############################
grand_cycle_No = grand_cycle_No + 1